### ISSUE TITLE
error: [MCP][actors-mcp-server] Connection failed: spawn npx ENOENT

### ISSUE THREAD

**Issue by orinciog** [apify/actors-mcp-server#66]
Hy!

I tried running actors-mcp-server on librechat.

I used the following simple configuration in librechat.yaml:

```
  actors-mcp-server:
    command: npx
    args:
      - -y
      - "@apify/actors-mcp-server"
    env:
      APIFY_TOKEN:  TOKEN
```

but running in librechat, I receive the following error:

`error: [MCP][actors-mcp-server] Connection failed: spawn npx ENOENT`

What can be the problem?

**Comment by zizake** [comment]
I am having the same problem. Maybe it is related to the mention on the website:
**[LibreChat](https://www.librechat.ai/) (stdio and SSE support (yet without Authorization header))**

However, if authorization is not implemented, is there a usecase where you can use in Librechat like this?

Thanks.

**Comment by orinciog** [comment]
The problem is a bug ([link1](https://github.com/modelcontextprotocol/typescript-sdk/issues/196), [link2](https://github.com/modelcontextprotocol/typescript-sdk/issues/216)) in  MCP typescript sdk, which affects also [librechat](https://github.com/danny-avila/LibreChat/pull/6648). 

The solution until workaround is merged in librechat or until the original bug is fixed is the following:

```
actors-mcp-server:
    command: sh
    args:
      - "-c"
      - "APIFY_TOKEN=TOKEN npx -y @apify/actors-mcp-server"
```

or

```
actors-mcp-server:
    command: npx
    args:
      - -y
      - "@apify/actors-mcp-server"
    env:
      PATH: #USE YOUR $PATH env value
      APIFY_TOKEN: TOKEN
```
